name: 💡 Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out all fields below.

  - type: input
    id: feature
    attributes:
      label: "✨ Describe the feature"
      description: "A clear and concise description of the feature."
      placeholder: "e.g. Generate AI-based product descriptions"
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "🔍 Problem it solves"
      description: "Why is this needed?"
      placeholder: "e.g. Merchants lack time to write descriptions manually"
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "📐 Proposed solution"
      description: "How should it work? (screens, API, logic)"
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "📊 Priority"
      description: "Select the priority level"
      options:
        - Low
        - Medium
        - High
      required: true

  - type: checkboxes
    id: related_areas
    attributes:
      label: "📦 Related areas"
      description: "Select modules affected by this feature"
      options:
        - label: Admin Panel
          value: admin
        - label: Merchant Dashboard
          value: merchant
        - label: Notifications
          value: notifications
        - label: Product Management
          value: product

  - type: textarea
    id: acceptance
    attributes:
      label: "✅ Acceptance criteria"
      description: "List the conditions that must be met for this feature to be considered done."
      required: true

  - type: input
    id: references
    attributes:
      label: "🔗 References (optional)"
      description: "Links to designs, docs, or related issues"
